#!/usr/bin/bash

# INIT VARS #################################
check_xmonad=$(neofetch | grep xmonad | wc -l)
check_qtile=$(neofetch | grep LG3D | wc -l)
isTrue=1
isFalse=0
# END VARS #################################

# Checking if XMonad is running
if [ "$check_xmonad" = "$isTrue" ] && [ "$check_qtile" = "$isFalse" ];
then
    rm ~/.xinitrc;
    ln -s ~/.config/xinitrc/qtilerc ~/.xinitrc;
    sudo pkill -9 -u sergio;
fi

# Checking if Qtile is running
if [ "$check_qtile" = "$isTrue" ] && [ "$check_xmonad" = "$isFalse" ];
then
    rm ~/.xinitrc;
    ln -s ~/.config/xinitrc/xmonadrc ~/.xinitrc;
    sudo pkill -9 -u sergio;
fi
